#!/bin/bash
#
# test simple command /bin/ls

command="/usr/bin/head -n 1 AUTHORS"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
output=`cat $OUTPUTFILE`
if [ "$output" == "# This file lists all individuals having contributed content to the repository." ]; then
       print_ok
else
       print_ko
fi

# clean up
stop_shell
rm -f $tmp_file